### ISSUE TITLE
bzr requests to configure your username

### ISSUE THREAD

**Issue by Mathiasdm** [mndrix/merge-this#4]
When running 'make bzr' for the first time, I got errors because bzr wanted me to configure my username. Ideally, this test suite should run self-contained without needing configuration from a user.

**Comment by mndrix** [comment]
It looks like bzr always wants to know the committer's name, even if `--author ...` is provided.

Others encountering this problem should run

    bzr whoami "Frank Chu <fchu@example.com>"

to resolve the problem locally.
